### ISSUE TITLE
Infinity armor's missing features

### ISSUE THREAD

**Issue by Froggy800** [abused/Avaritia-Additions#4]
(This is just to provide a list of currently missing features, feel free to close the issue if this isn't needed)
-Infinity boots don't give jump boost
-Helmet doesn't keep hunger filled
-Pants don't prevent catching on fire
-The full Infinity Armor set doesn't prevent knockback from attacks

The infinity armor doesn't prevent the following damage:
-Void damage
-Permanent health damage from Extra utilities 2's Kikoku; the other damage types are prevented
-Draconic evolution's Chaos Guardian's homing attacks (the fireball barrage doesn't deal damage)
-Draconic evolution's explosions (Chaos Island's self destruction and Draconic reactor meltdown)

Lastly, not a missing feature but a suggestion: pants don't give step assist

**Comment by alothmanmoe** [comment]
Please keep it to 1 issue instead of making multiple put them in 1, as i have tested in my dev environment for the list of missing features you created they work perfectly fine, ill have to see whats going on with that.
The damage protection huh, i have tested with the chaos dragon, damn DE made it op, ill have to see if i should make it protect against its homing attacks as it would make it too easy.
explosions huh, damn it DE, ill have to go see what type of damage their dealing and ill have to protect against it,
step assist is coming :P

**Comment by Boolyman** [comment]
I really hope you choose to make the armor resistant to the DE Chaos Guardian... There is not a single mod out there, other than DE, that provides an option to negate that damage.  The whole reason I got excited about avaritia is because it finally gives an option other than DE for our end game. 

As for the other stuff mentioned... I could care less about hunger, or jump height... there are potions, enchants, etc... for all of that.  I simply want something that will finally protect against chaos guardian and void damage sources.

**Comment by alothmanmoe** [comment]
OK step assist added, i wont protect against the ExU permanent heart removal, that affects the player directly avoiding armor, working on Void Damage and Chaos Dragon damage, and on preventing knockback

**Comment by alothmanmoe** [comment]
All right releasing a new version in about an hour
